// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQU9Bc9vNAD9j4FXkwf4Eu0OokbAE7Q-k',
    appId: '1:748477872997:android:0e123172769e20f6e3bf8c',
    messagingSenderId: '748477872997',
    projectId: 'dht11-fb8a7',
    databaseURL: 'https://dht11-fb8a7-default-rtdb.firebaseio.com',
    storageBucket: 'dht11-fb8a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcrdpN2ghk6YdfBPVeQudfA_WAT-kkEqI',
    appId: '1:748477872997:ios:5759533527a2a51be3bf8c',
    messagingSenderId: '748477872997',
    projectId: 'dht11-fb8a7',
    databaseURL: 'https://dht11-fb8a7-default-rtdb.firebaseio.com',
    storageBucket: 'dht11-fb8a7.appspot.com',
    androidClientId: '748477872997-20fnbcspdkdm56aslel3id5ke2gcalth.apps.googleusercontent.com',
    iosClientId: '748477872997-6o4tmkno5jnimfbieplddudcf52tbbc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );
}
