import 'package:chat_application/models/gesture.dart';

List<Gesture> drive = [
  Gesture(objectKey: 'A', objectValue: 'Move Forward', objectUse: true),
  Gesture(objectKey: 'B', objectValue: 'Move Forward', objectUse: true),
  Gesture(objectKey: 'C', objectValue: 'Move Backward', objectUse: true),
  Gesture(objectKey: 'D', objectValue: 'Move Backward', objectUse: true),
  Gesture(objectKey: 'E', objectValue: 'Move Backward', objectUse: true),
  Gesture(objectKey: 'F', objectValue: "Turn Left", objectUse: true),
  Gesture(objectKey: 'G', objectValue: "Turn Left", objectUse: true),
  Gesture(objectKey: 'H', objectValue: 'Turn Right', objectUse: true),
  Gesture(objectKey: 'I', objectValue: "Rotate Left", objectUse: true),
  Gesture(objectKey: 'J', objectValue: "Rotate Left", objectUse: true),
  Gesture(objectKey: 'K', objectValue: 'Rotate Right', objectUse: true),
  Gesture(objectKey: 'L', objectValue: 'Rotate Right', objectUse: true),
  Gesture(objectKey: 'M', objectValue: 'Stop', objectUse: true),
  Gesture(objectKey: 'N', objectValue: 'Stop', objectUse: true),
  Gesture(objectKey: 'O', objectValue: 'Location', objectUse: true),
  Gesture(objectKey: 'P', objectValue: "Location", objectUse: true),
  Gesture(objectKey: 'Q', objectValue: "Location", objectUse: true),
  Gesture(objectKey: 'R', objectValue: 'Location', objectUse: true),
  Gesture(objectKey: 'S', objectValue: 'Main Menu', objectUse: true),
  Gesture(objectKey: 'T', objectValue: "Main Menu", objectUse: true),
  Gesture(objectKey: 'U', objectValue: "Main Menu", objectUse: true),
  Gesture(objectKey: 'V', objectValue: "Main Menu", objectUse: true),
  Gesture(objectKey: 'W', objectValue: 'Connections', objectUse: true),
  Gesture(objectKey: 'X', objectValue: 'Connections', objectUse: true),
  Gesture(objectKey: 'Y', objectValue: 'Connections', objectUse: true),
  Gesture(objectKey: 'Z', objectValue: 'Connections', objectUse: true),
];
